### ISSUE TITLE
Unable to compile on OSX 64bit

### ISSUE THREAD

**Issue by testalt** [CzarekTomczak/cef2go#23]
I have followed all steps mentioned in the Readme, downloaded 64bit CEF binaries and placed them correctly in the Release folder, this is the "make" command output  : 

Copying CEF framework directory to Release/tmp
go install -x cef
WORK=/var/folders/c6/snmkcstx5t927hn229tjvg480000gn/T/go-build794425398
rm -f Release/cef2go.app/Contents/MacOS/cef2go
go build -x -ldflags "-r ." -o Release/cef2go.app/Contents/MacOS/cef2go src/main_darwin.go
WORK=/var/folders/c6/snmkcstx5t927hn229tjvg480000gn/T/go-build373331596
mkdir -p $WORK/cocoa/_obj/
mkdir -p $WORK/
cd /Users/tony/go/src/github.com/CzarekTomczak/cef2go/src/cocoa
CGO_LDFLAGS="-F/Users/tony/go/src/github.com/CzarekTomczak/cef2go/Release/tmp" "-framework" "Cocoa" "-framework" "cef" "-framework" "Cocoa" "-framework" "Cocoa" /usr/local/go/pkg/tool/darwin_amd64/cgo -objdir $WORK/cocoa/_obj/ -- -I $WORK/cocoa/_obj/ -I./../../ -x objective-c -I./../../ -x objective-c cocoa.go export.go
/usr/local/go/pkg/tool/darwin_amd64/6c -F -V -w -trimpath $WORK -I $WORK/cocoa/_obj/ -I /usr/local/go/pkg/darwin_amd64 -o $WORK/cocoa/_obj/_cgo_defun.6 -D GOOS_darwin -D GOARCH_amd64 $WORK/cocoa/_obj/_cgo_defun.c
clang -I . -I. -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -print-libgcc-file-name
clang -I . -I. -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/cocoa/_obj/ -g -O2 -I./../../ -x objective-c -I./../../ -x objective-c -o $WORK/cocoa/_obj/_cgo_main.o -c $WORK/cocoa/_obj/_cgo_main.c
clang -I . -I. -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/cocoa/_obj/ -g -O2 -I./../../ -x objective-c -I./../../ -x objective-c -o $WORK/cocoa/_obj/_cgo_export.o -c $WORK/cocoa/_obj/_cgo_export.c
clang -I . -I. -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/cocoa/_obj/ -g -O2 -I./../../ -x objective-c -I./../../ -x objective-c -o $WORK/cocoa/_obj/cocoa.cgo2.o -c $WORK/cocoa/_obj/cocoa.cgo2.c
# cocoa
src/cocoa/cocoa.go:30:5: warning: implicit declaration of function '_GoDestroySignal' is invalid in C99 [-Wimplicit-function-declaration]
clang -I . -I. -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -I $WORK/cocoa/_obj/ -g -O2 -I./../../ -x objective-c -I./../../ -x objective-c -o $WORK/cocoa/_obj/export.cgo2.o -c $WORK/cocoa/_obj/export.cgo2.c
clang -I . -I. -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -o $WORK/cocoa/_obj/_cgo_.o $WORK/cocoa/_obj/_cgo_main.o $WORK/cocoa/_obj/_cgo_export.o $WORK/cocoa/_obj/cocoa.cgo2.o $WORK/cocoa/_obj/export.cgo2.o -F/Users/tony/go/src/github.com/CzarekTomczak/cef2go/Release/tmp -framework Cocoa -framework cef -framework Cocoa -framework Cocoa
/usr/local/go/pkg/tool/darwin_amd64/cgo -objdir $WORK/cocoa/_obj/ -dynimport $WORK/cocoa/_obj/_cgo_.o -dynout $WORK/cocoa/_obj/_cgo_import.c
/usr/local/go/pkg/tool/darwin_amd64/6c -F -V -w -trimpath $WORK -I $WORK/cocoa/_obj/ -I /usr/local/go/pkg/darwin_amd64 -o $WORK/cocoa/_obj/_cgo_import.6 -D GOOS_darwin -D GOARCH_amd64 $WORK/cocoa/_obj/_cgo_import.c
clang -I . -I. -fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common -o $WORK/cocoa/_obj/_all.o $WORK/cocoa/_obj/_cgo_export.o $WORK/cocoa/_obj/cocoa.cgo2.o $WORK/cocoa/_obj/export.cgo2.o -F/Users/tony/go/src/github.com/CzarekTomczak/cef2go/Release/tmp -Wl,-r -nostdlib
/usr/local/go/pkg/tool/darwin_amd64/6g -o $WORK/cocoa.a -trimpath $WORK -p cocoa -D _/Users/tony/go/src/github.com/CzarekTomczak/cef2go/src/cocoa -I $WORK -pack $WORK/cocoa/_obj/_cgo_gotypes.go $WORK/cocoa/_obj/cocoa.cgo1.go $WORK/cocoa/_obj/export.cgo1.go
pack r $WORK/cocoa.a $WORK/cocoa/_obj/_cgo_import.6 $WORK/cocoa/_obj/_cgo_defun.6 $WORK/cocoa/_obj/_all.o # internal
mkdir -p $WORK/command-line-arguments/_obj/
mkdir -p Release/cef2go.app/Contents/MacOS/
cd /Users/tony/go/src/github.com/CzarekTomczak/cef2go/src
/usr/local/go/pkg/tool/darwin_amd64/6g -o $WORK/command-line-arguments.a -trimpath $WORK -p command-line-arguments -complete -D _/Users/tony/go/src/github.com/CzarekTomczak/cef2go/src -I $WORK -I /Users/tony/go/src/github.com/CzarekTomczak/cef2go/pkg/darwin_amd64 -pack ./main_darwin.go
cd .
/usr/local/go/pkg/tool/darwin_amd64/6l -o Release/cef2go.app/Contents/MacOS/cef2go -L $WORK -L /Users/tony/go/src/github.com/CzarekTomczak/cef2go/pkg/darwin_amd64 -r . -extld=clang -extldflags=-I. $WORK/command-line-arguments.a
install_name_tool -change @executable_path/Chromium\ Embedded\ Framework @executable_path/../Frameworks/Chromium\ Embedded\ Framework.framework/Chromium\ Embedded\ Framework Release/cef2go.app/Contents/MacOS/cef2go
cp -f Release/example.html Release/cef2go.app/Contents/MacOS/example.html
cd Release/cef2go.app/Contents/MacOS && ./cef2go && cd ../../../../
dyld: Library not loaded: @executable_path/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Users/tony/go/src/github.com/CzarekTomczak/cef2go/Release/cef2go.app/Contents/MacOS/./cef2go
  Reason: image not found
/bin/sh: line 1: 58752 Trace/BPT trap: 5       ./cef2go
make[1]: *** [Darwin] Error 133
make: *** [detect_os] Error 2

Any idea about how to solve the problem ?

**Comment by CzarekTomczak** [comment]
Please use Forum for reporting problems or asking questions. This post may be of help: https://groups.google.com/d/msg/cef2go/WAxL8LEAr7E/Oqfjw64bZDoJ
