### ISSUE TITLE
Update CEF binaries

### ISSUE THREAD

**Issue by FThomas-ram** [CzarekTomczak/cef2go#27]
Hi everyone,

I tried to update the CEF binaries, because "CEF 3 branch 1750 revision 1590" is quite outdated. So I copied the same files from a newer version of CEF. When I tried to build the app, CEF complains that it could not load its .pak files - though they are in the "cwd" directory.

So what's the proper way to update CEF in CEF2go?

Thanks in advance!

**Comment by CzarekTomczak** [comment]
Please ask questions on the Forum. See Issue #16. See also the [paperlesspost/cef2go](https://github.com/paperlesspost/cef2go) fork which uses a newer CEF. It has its own instructions for updating CEF: https://github.com/paperlesspost/cef2go#updating-the-cef-version
